service: football-competition

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource: "arn:aws:dynamodb:ap-southeast-1:*:table/footballCompetition"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
      Resource: "arn:aws:dynamodb:ap-southeast-1:*:table/footballCompetition/index/*"

functions:
  base:
    handler: src/app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: "{proxy+}"
          method: ANY
          cors: true
  # getTeam:
  #   handler: src/handler.getTeam
  #   events:
  #     - http:
  #         path: /team/{teamName}
  #         method: get
  #         cors: true
  # updateMatch:
  #   handler: src/handler.updateMatch
  #   events:
  #     - http:
  #         path: /team/{teamName}
  #         method: get
  #         cors: true

resources:
  Resources:
    footballCompetition:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: footballCompetition
        AttributeDefinitions:
          - AttributeName: teamName
            AttributeType: S
        KeySchema:
          - AttributeName: teamName
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
